// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf6hh32N6p0suCk0Pwqs-rZGQfCjKZnpQ',
    appId: '1:176783989801:web:8a13ae863de67aa3359038',
    messagingSenderId: '176783989801',
    projectId: 'twine-3b540',
    authDomain: 'twine-3b540.firebaseapp.com',
    storageBucket: 'twine-3b540.appspot.com',
    measurementId: 'G-M6PV0Q420F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh8AMKIbVMcn_K8FCU8EHY3yT-4g4yUsI',
    appId: '1:176783989801:android:3e6b18e841657e4e359038',
    messagingSenderId: '176783989801',
    projectId: 'twine-3b540',
    storageBucket: 'twine-3b540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnaSy-hB4ll-HsN9rI5iPRnDXQI1LrHtY',
    appId: '1:176783989801:ios:ae283d849954b491359038',
    messagingSenderId: '176783989801',
    projectId: 'twine-3b540',
    storageBucket: 'twine-3b540.appspot.com',
    iosBundleId: 'com.mycompany.redthread',
  );
}
